
splash:

    connections:
        akeneo:    
            name:           Akeneo for Splash
            id:             ThisIsSplashWsId
            key:            ThisIsYourEncryptionKeyForSplash
            host:           http://toolkit.akeneo.local/ws/soap
            config:
                locale:         en_US
                travis:         true
                images:
                    - { code: 'picture', label: 'meta_title' }
                    - 'image'
                    - 'image_2'
                    - 'image_3'
                    - 'image_4',
                    - 'variation_image'
                    - 'variation_image_2'
                    - 'variation_image_3'
                    - 'variation_image_4'
    test:
        VAT:                0