
splash:
    connections:
        akeneo:    
            name:           Akeneo for Splash
            id:             ThisIsSplashWsId
            key:            ThisIsYourEncryptionKeyForSplash
            host:           http://toolkit.akeneo.local/ws/soap
            config:
                locale:         en_US
                channel:        ecommerce
                currency:       EUR
                images:         ['image', 'picture', 'variation_image']
                categories:     ["master_women_shirts"]
                travis:         true
                catalog_mode:   true
                infos:
                    ico:        '%kernel.root_dir%/../vendor/splash/akeneo-bundle/src/Resources/img/logo.png'
                    logo:       http://docker.akeneo.local/bundles/pimui/images/info-user.png
    test:
        VAT:                0