
splash:
    connections:
        akeneo:    
            name:           Akeneo for Splash
            id:             ThisIsSplashWsId
            key:            ThisIsYourEncryptionKeyForSplash
            host:           http://toolkit.akeneo.local/ws/soap
            config:
                locale:         en_US
                channel:        ecommerce
                currency:       EUR
                images:         ['image', 'picture', 'variation_image']
                travis:         true
                infos:
                    logo:       http://docker.akeneo.local/bundles/pimui/images/info-user.png
    test:
        VAT:                0