
########################################################################
# Splash Akeneo Products Management Services
########################################################################

services:
    _defaults:
        autowire: true

    ########################################################################
    # Akeneo Products Data Transformer
    # Convert In/Out Doctrine Objects Fields to Splash Standard Format
    splash.akeneo.object.product:
        class:      Splash\Akeneo\Objects\Product
        arguments:  
            -   "@pim_catalog.repository.product"
            -   "@pim_catalog.repository.category"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Product" }  
            
    ########################################################################
    # Akeneo Products Crud Manager
    Splash\Akeneo\Services\CrudService:
        arguments:
            -   "@pim_catalog.repository.product"
            -   "@pim_catalog.builder.product"
            -   "@pim_catalog.validator.product"
            -   "@pim_catalog.saver.product"
            -   "@pim_catalog.saver.product_model"
            -   "@pim_catalog.remover.product"

    ########################################################################
    # Akeneo Products Crud Manager
    Splash\Akeneo\Services\AttributesManager:
        arguments:
            -   "@pim_catalog.updater.property_setter"
            -   "@pim_catalog.repository.attribute"
            -   "@pim_catalog.saver.attribute_option"
            -   "@akeneo_measure.manager"

    ########################################################################
    # Akeneo Products Variant Manager
    Splash\Akeneo\Services\VariantsManager:
        class:      Splash\Akeneo\Services\VariantsManager
        arguments:
            -   "@pim_catalog.repository.family_variant"
            
    ########################################################################
    # Akeneo Products Models Manager
    Splash\Akeneo\Services\ModelsManager:
        arguments:
            -   "@pim_catalog.factory.product_model"
            -   "@pim_catalog.validator.product_model"
            -   "@pim_catalog.saver.product_model"
            -   "@pim_catalog.remover.product_model"

    ########################################################################
    # Akeneo Products Images Gallery Manager
    Splash\Akeneo\Services\GalleryManager: ~

    ########################################################################
    # Akeneo Products Event EventSubscriber
    splash.akeneo.product.events:
        class:      Splash\Akeneo\EventSubscriber\DoctrineEventsSubscriber
        autowire:   true
        arguments:
            -   "@splash.connectors.manager"
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }
            - { name: kernel.event_listener, event: pim_installer.pre_load_fixture, method: setAllStatesDisabled }
            - { name: kernel.event_listener, event: pim_installer.pre_load_fixtures, method: setAllStatesDisabled }

    ########################################################################
    # Akeneo Products Batch EventSubscriber
    splash.akeneo.product.batch.events:
        class:      Splash\Akeneo\EventSubscriber\StorageEventsSubscriber
        autowire:   true
        arguments:
            -   "@splash.connectors.manager"
        tags:
            - { name: kernel.event_subscriber }
            