services:
    _defaults:
        autowire: true

    ########################################################################
    # Akeneo Products Data Transformer
    # Convert In/Out Doctrine Objects Fields to Splash Standard Format
    splash.akeneo.object.product:
        class:      Splash\Akeneo\Objects\Product
        arguments:  
            -   "@pim_catalog.repository.product"
            -   "@splash.akeneo.product.crud"  
            -   "@splash.akeneo.product.attributes"
            -   "@splash.akeneo.product.variants"
            -   "@splash.akeneo.product.files"
            -   "@splash.akeneo.locales"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Product" }  
            
    ########################################################################
    # Akeneo Products Crud Manager
    splash.akeneo.product.crud:
        class:      Splash\Akeneo\Services\CrudService
        arguments:  
            -   "@pim_catalog.repository.product"
            -   "@pim_catalog.builder.product"
            -   "@pim_catalog.validator.product"
            -   "@pim_catalog.saver.product"
            -   "@pim_catalog.remover.product"
            -   "@splash.akeneo.product.variants"
            -   "@splash.akeneo.product.models"

    ########################################################################
    # Akeneo Products Crud Manager
    splash.akeneo.product.attributes:
        class:      Splash\Akeneo\Services\AttributesManager
        arguments:  
            -   "@pim_catalog.updater.property_setter"
            -   "@pim_catalog.repository.attribute"
            -   "@akeneo_measure.manager"
            -   "@splash.akeneo.product.files"
            -   "@splash.akeneo.locales"  

    ########################################################################
    # Akeneo Products Variant Manager
    splash.akeneo.product.variants:
        class:      Splash\Akeneo\Services\VariantsManager
        arguments:  
            -   "@splash.akeneo.locales"
            -   "@pim_catalog.repository.family_variant"
            
    ########################################################################
    # Akeneo Products Models Manager
    splash.akeneo.product.models:
        class:      Splash\Akeneo\Services\ModelsManager
        arguments:  
            -   "@pim_catalog.factory.product_model"
            -   "@pim_catalog.validator.product_model"
            -   "@pim_catalog.saver.product_model"
            -   "@pim_catalog.remover.product_model"
            -   "@splash.akeneo.product.variants"

    ########################################################################
    # Akeneo Connector Products Files Manager
    splash.akeneo.product.files:
        class:      Splash\Akeneo\Services\FilesManager
        arguments:  
            -   "@router"
            -   "@akeneo_file_storage.file_storage.file.file_storer"
            -   "@akeneo_file_storage.remover.file"
            -   "@akeneo_file_storage.repository.file_info"
            -   "@oneup_flysystem.mount_manager"


    ########################################################################
    # Akeneo Products Event EventSubscriber
    splash.akeneo.product.events:
        class:      Splash\Akeneo\EventSubscriber\DoctrineEventsSubscriber
        autowire:   true
        arguments:
            -   "@splash.connectors.manager"
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }
            - { name: kernel.event_listener, event: pim_installer.pre_load_fixture, method: setAllStatesDisabled }
            - { name: kernel.event_listener, event: pim_installer.pre_load_fixtures, method: setAllStatesDisabled }

    ########################################################################
    # Akeneo Products Batch EventSubscriber
    splash.akeneo.product.batch.events:
        class:      Splash\Akeneo\EventSubscriber\StorageEventsSubscriber
        autowire:   true
        arguments:
            -   "@splash.connectors.manager"
        tags:
            - { name: kernel.event_subscriber }

    ########################################################################
    # Akeneo Connector Locales Manager
    splash.akeneo.locales:
        class:      Splash\Akeneo\Services\LocalesManager
        arguments:  
            -   "@pim_catalog.repository.locale"
            -   "@translator"
            