
########################################################################
# Splash Akeneo Tooling Services
########################################################################

services:
    _defaults:
        autowire: true

    ########################################################################
    # Akeneo Configuration Manager
    Splash\Akeneo\Services\Configuration:
        arguments:
            - "@pim_catalog.repository.channel"

    ########################################################################
    # Akeneo Files Manager
    Splash\Akeneo\Services\FilesManager:
        arguments:
            -   "@akeneo_file_storage.file_storage.file.file_storer"
            -   "@akeneo_file_storage.remover.file"
            -   "@akeneo_file_storage.repository.file_info"
            -   "@oneup_flysystem.mount_manager"

    ########################################################################
    # Akeneo Documents Manager
    Splash\Akeneo\Services\DocumentsManager:
        arguments:
            -   "@akeneo_file_storage.file_storage.file.file_storer"
            -   "@akeneo_file_storage.remover.file"
            -   "@akeneo_file_storage.repository.file_info"
            -   "@oneup_flysystem.mount_manager"

    ########################################################################
    # Akeneo Connector Locales Manager
    Splash\Akeneo\Services\LocalesManager:
        arguments:
            -   "@pim_catalog.repository.locale"
