
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Availables Connector Connections
################################################################################    

    connections:
        
########################################################################
# Generic Soap Connection (Test & Debug your Generic Splash Servers) 
        generic:
            id:                 ThisIsSplashWsId
            key:                ThisIsYourEncryptionKeyForSplash
            name:               My Akeneo Server
            host:               false
            connector:          soap
            config:  
                Name:               Akeneo Docker ;-)
                WsIdentifier:       ThisIsSplashWsId
                WsEncryptionKey:    ThisIsYourEncryptionKeyForSplash                
                WsHost:             http://v7.akeneo.local
                WsPath:             /ws/splash
                Extended:           true
